// All countries
// length 252
export class NationalityConst {
	public static List = [
		{ name: "Afghanistan", code: "AF" },
		{ name: "Quần đảo Aland", code: "AX" },
		{ name: "Albania", code: "AL" },
		{ name: "Algeria", code: "DZ" },
		{ name: "American Samoa", code: "AS" },
		{ name: "Andorra", code: "AD" },
		{ name: "Angola", code: "AO" },
		{ name: "Anguilla", code: "AI" },
		{ name: "Nam Cực", code: "AQ" },
		{ name: "Antigua và Barbuda", code: "AG" },
		{ name: "Argentina", code: "AR" },
		{ name: "Armenia", code: "AM" },
		{ name: "Aruba", code: "AW" },
		{ name: "Châu Úc", code: "AU" },
		{ name: "Áo", code: "AT" },
		{ name: "Azerbaijan", code: "AZ" },
		{ name: "Bahamas", code: "BS" },
		{ name: "Bahrain", code: "BH" },
		{ name: "Bangladesh", code: "BD" },
		{ name: "Barbados", code: "BB" },
		{ name: "Belarus", code: "BY" },
		{ name: "nước Bỉ", code: "BE" },
		{ name: "Belize", code: "BZ" },
		{ name: "Benin", code: "BJ" },
		{ name: "Bermuda", code: "BM" },
		{ name: "Bhutan", code: "BT" },
		{ name: "Bolivia", code: "BO" },
		{ name: "Bonaire, Sint Eustatius và Saba", code: "BQ" },
		{ name: "Bosnia và Herzegovina", code: "BA" },
		{ name: "Botswana", code: "BW" },
		{ name: "Đảo Bouvet", code: "BV" },
		{ name: "Brazil", code: "BR" },
		{ name: "Lãnh thổ Ấn Độ Dương thuộc Anh", code: "IO" },
		{ name: "Vương quốc Bru-nây", code: "BN" },
		{ name: "Bungari", code: "BG" },
		{ name: "Burkina Faso", code: "BF" },
		{ name: "Burundi", code: "BI" },
		{ name: "Campuchia", code: "KH" },
		{ name: "Cameroon", code: "CM" },
		{ name: "Canada", code: "CA" },
		{ name: "Cape Verde", code: "CV" },
		{ name: "Quần đảo Cayman", code: "KY" },
		{ name: "Cộng hòa trung phi", code: "CF" },
		{ name: "Chad", code: "TD" },
		{ name: "Chile", code: "CL" },
		{ name: "Trung Quốc", code: "CN" },
		{ name: "Đảo giáng sinh", code: "CX" },
		{ name: "Quần đảo Cocos (Keeling)", code: "CC" },
		{ name: "Colombia", code: "CO" },
		{ name: "Comoros", code: "KM" },
		{ name: "Congo", code: "CG" },
		{ name: "Congo, Cộng hòa Dân chủ Congo", code: "CD" },
		{ name: "Quần đảo Cook", code: "CK" },
		{ name: "Costa Rica", code: "CR" },
		{ name: "Cote D'Ivoire", code: "CI" },
		{ name: "Croatia", code: "HR" },
		{ name: "Cuba", code: "CU" },
		{ name: "rượu cam bì", code: "CW" },
		{ name: "Síp", code: "CY" },
		{ name: "Cộng hòa Séc", code: "CZ" },
		{ name: "Đan mạch", code: "DK" },
		{ name: "Djibouti", code: "DJ" },
		{ name: "Dominica", code: "DM" },
		{ name: "Cộng hòa Dominica", code: "DO" },
		{ name: "Ecuador", code: "EC" },
		{ name: "Ai cập", code: "EG" },
		{ name: "El Salvador", code: "SV" },
		{ name: "Equatorial Guinea", code: "GQ" },
		{ name: "Eritrea", code: "ER" },
		{ name: "Estonia", code: "EE" },
		{ name: "Ethiopia", code: "ET" },
		{ name: "Quần đảo Falkland (Malvinas)", code: "FK" },
		{ name: "Quần đảo Faroe", code: "FO" },
		{ name: "Fiji", code: "FJ" },
		{ name: "Phần Lan", code: "FI" },
		{ name: "Nước pháp", code: "FR" },
		{ name: "Guiana thuộc Pháp", code: "GF" },
		{ name: "Polynesia thuộc Pháp", code: "PF" },
		{ name: "Lãnh thổ phía Nam của Pháp", code: "TF" },
		{ name: "Gabon", code: "GA" },
		{ name: "Gambia", code: "GM" },
		{ name: "Georgia", code: "GE" },
		{ name: "nước Đức", code: "DE" },
		{ name: "Ghana", code: "GH" },
		{ name: "Gibraltar", code: "GI" },
		{ name: "Hy Lạp", code: "GR" },
		{ name: "Greenland", code: "GL" },
		{ name: "Grenada", code: "GD" },
		{ name: "Guadeloupe", code: "GP" },
		{ name: "Guam", code: "GU" },
		{ name: "Guatemala", code: "GT" },
		{ name: "Guernsey", code: "GG" },
		{ name: "Guinea", code: "GN" },
		{ name: "Guinea-Bissau", code: "GW" },
		{ name: "Guyana", code: "GY" },
		{ name: "Haiti", code: "HT" },
		{ name: "Đảo Heard và Quần đảo McDonald", code: "HM" },
		{ name: "Tòa thánh (Nhà nước thành phố Vatican)", code: "VA" },
		{ name: "Honduras", code: "HN" },
		{ name: "Hồng Kông", code: "HK" },
		{ name: "Hungary", code: "HU" },
		{ name: "Nước Iceland", code: "IS" },
		{ name: "Ấn Độ", code: "IN" },
		{ name: "Indonesia", code: "ID" },
		{ name: "Iran (Cộng hòa Hồi giáo", code: "IR" },
		{ name: "I-rắc", code: "IQ" },
		{ name: "Ireland", code: "IE" },
		{ name: "Đảo Man", code: "IM" },
		{ name: "Người israel", code: "IL" },
		{ name: "Nước Ý", code: "IT" },
		{ name: "Jamaica", code: "JM" },
		{ name: "Nhật Bản", code: "JP" },
		{ name: "Jersey", code: "JE" },
		{ name: "Jordan", code: "JO" },
		{ name: "Kazakhstan", code: "KZ" },
		{ name: "Kenya", code: "KE" },
		{ name: "Kiribati", code: "KI" },
		{ name: "Hàn Quốc, Cộng hòa Dân chủ Nhân dân", code: "KP" },
		{ name: "Hàn Quốc, Cộng hòa", code: "KR" },
		{ name: "Kosovo", code: "XK" },
		{ name: "Kuwait", code: "KW" },
		{ name: "Kyrgyzstan", code: "KG" },
		{ name: "Cộng hòa Dân chủ nhân dân Lào", code: "LA" },
		{ name: "Latvia", code: "LV" },
		{ name: "Lebanon", code: "LB" },
		{ name: "Lesotho", code: "LS" },
		{ name: "Liberia", code: "LR" },
		{ name: "Libyan Arab Jamahiriya", code: "LY" },
		{ name: "Liechtenstein", code: "LI" },
		{ name: "Lithuania", code: "LT" },
		{ name: "Luxembourg", code: "LU" },
		{ name: "Macao", code: "MO" },
		{ name: "Macedonia, Cộng hòa Nam Tư cũ của", code: "MK" },
		{ name: "Madagascar", code: "MG" },
		{ name: "Malawi", code: "MW" },
		{ name: "Malaysia", code: "MY" },
		{ name: "Maldives", code: "MV" },
		{ name: "Mali", code: "ML" },
		{ name: "Malta", code: "MT" },
		{ name: "đảo Marshall", code: "MH" },
		{ name: "Martinique", code: "MQ" },
		{ name: "Mauritania", code: "MR" },
		{ name: "Mauritius", code: "MU" },
		{ name: "Mayotte", code: "YT" },
		{ name: "Mexico", code: "MX" },
		{ name: "Micronesia, Liên bang", code: "FM" },
		{ name: "Moldova, Cộng hòa", code: "MD" },
		{ name: "Monaco", code: "MC" },
		{ name: "Mông Cổ", code: "MN" },
		{ name: "Montenegro", code: "ME" },
		{ name: "Montserrat", code: "MS" },
		{ name: "Maroc", code: "MA" },
		{ name: "Mozambique", code: "MZ" },
		{ name: "Myanmar", code: "MM" },
		{ name: "Namibia", code: "NA" },
		{ name: "Nauru", code: "NR" },
		{ name: "Nepal", code: "NP" },
		{ name: "nước Hà Lan", code: "NL" },
		{ name: "Đảo Antilles của Hà Lan", code: "AN" },
		{ name: "New Caledonia", code: "NC" },
		{ name: "New Zealand", code: "NZ" },
		{ name: "Nicaragua", code: "NI" },
		{ name: "Niger", code: "NE" },
		{ name: "Nigeria", code: "NG" },
		{ name: "Niue", code: "NU" },
		{ name: "Đảo Norfolk", code: "NF" },
		{ name: "Quần đảo Bắc Mariana", code: "MP" },
		{ name: "Na Uy", code: "NO" },
		{ name: "Oman", code: "OM" },
		{ name: "Pakistan", code: "PK" },
		{ name: "Palau", code: "PW" },
		{ name: "Lãnh thổ Palestine, bị chiếm đóng", code: "PS" },
		{ name: "Panama", code: "PA" },
		{ name: "Papua New Guinea", code: "PG" },
		{ name: "Paraguay", code: "PY" },
		{ name: "Peru", code: "PE" },
		{ name: "Phi-líp-pin", code: "PH" },
		{ name: "Pitcairn", code: "PN" },
		{ name: "Ba lan", code: "PL" },
		{ name: "Bồ Đào Nha", code: "PT" },
		{ name: "Puerto Rico", code: "PR" },
		{ name: "Qatar", code: "QA" },
		{ name: "Sum họp", code: "RE" },
		{ name: "Romania", code: "RO" },
		{ name: "Liên bang Nga", code: "RU" },
		{ name: "Rwanda", code: "RW" },
		{ name: "Saint Barthelemy", code: "BL" },
		{ name: "Saint Helena", code: "SH" },
		{ name: "Saint Kitts và Nevis", code: "KN" },
		{ name: "Saint Lucia", code: "LC" },
		{ name: "Saint martin", code: "MF" },
		{ name: "Saint Pierre và Miquelon", code: "PM" },
		{ name: "Saint Vincent và Grenadines", code: "VC" },
		{ name: "Samoa", code: "WS" },
		{ name: "San Marino", code: "SM" },
		{ name: "Sao Tome và Principe", code: "ST" },
		{ name: "Ả Rập Saudi", code: "SA" },
		{ name: "Senegal", code: "SN" },
		{ name: "Xéc-bi-a", code: "RS" },
		{ name: "Serbia và Montenegro", code: "CS" },
		{ name: "Seychelles", code: "SC" },
		{ name: "Sierra Leone", code: "SL" },
		{ name: "Singapore", code: "SG" },
		{ name: "St Martin", code: "SX" },
		{ name: "Xlô-va-ki-a", code: "SK" },
		{ name: "Slovenia", code: "SI" },
		{ name: "Quần đảo Solomon", code: "SB" },
		{ name: "Somalia", code: "SO" },
		{ name: "Nam Phi", code: "ZA" },
		{ name: "Nam Georgia và Quần đảo Nam Sandwich", code: "GS" },
		{ name: "phía nam Sudan", code: "SS" },
		{ name: "Tây ban nha", code: "ES" },
		{ name: "Sri Lanka", code: "LK" },
		{ name: "Sudan", code: "SD" },
		{ name: "Suriname", code: "SR" },
		{ name: "Svalbard và Jan Mayen", code: "SJ" },
		{ name: "Swaziland", code: "SZ" },
		{ name: "Thụy Điển", code: "SE" },
		{ name: "Thụy sĩ", code: "CH" },
		{ name: "Cộng Hòa Arab Syrian", code: "SY" },
		{ name: "Đài Loan, tỉnh của Trung Quốc", code: "TW" },
		{ name: "Tajikistan", code: "TJ" },
		{ name: "Tanzania, Cộng hòa Thống nhất", code: "TZ" },
		{ name: "nước Thái Lan", code: "TH" },
		{ name: "Timor-Leste", code: "TL" },
		{ name: "Đi", code: "TG" },
		{ name: "Tokelau", code: "TK" },
		{ name: "Tonga", code: "TO" },
		{ name: "Trinidad và Tobago", code: "TT" },
		{ name: "Tunisia", code: "TN" },
		{ name: "gà tây", code: "TR" },
		{ name: "Turkmenistan", code: "TM" },
		{ name: "Quần đảo Turks và Caicos", code: "TC" },
		{ name: "Tuvalu", code: "TV" },
		{ name: "Uganda", code: "UG" },
		{ name: "Ukraine", code: "UA" },
		{ name: "các Tiểu Vương Quốc Ả Rập Thống Nhất", code: "AE" },
		{ name: "Vương quốc Anh", code: "GB" },
		{ name: "Hoa Kỳ", code: "US" },
		{ name: "Các đảo nhỏ xa xôi hẻo lánh của Hoa Kỳ", code: "UM" },
		{ name: "Uruguay", code: "UY" },
		{ name: "U-dơ-bê-ki-xtan", code: "UZ" },
		{ name: "Vanuatu", code: "VU" },
		{ name: "Venezuela", code: "VE" },
		{ name: "Việt Nam", code: "VN" },
		{ name: "Quần đảo Virgin thuộc Anh", code: "VG" },
		{ name: "Quần đảo Virgin, Hoa Kỳ", code: "VI" },
		{ name: "Wallis và Futuna", code: "WF" },
		{ name: "Phía tây Sahara", code: "EH" },
		{ name: "Yemen", code: "YE" },
		{ name: "Zambia", code: "ZM" },
		{ name: "Zimbabwe", code: "ZW" },
	];
}
